[package]
name = "client"
version = "0.1.0"
edition = "2024"

[dependencies]
appconfig = { path = "../appconfig" }
reqwest = "0.12.20"
tokio = { version = "1.45.1", features = ["macros", "rt-multi-thread"] }
