---
server:
  port: 8000

client:
  # rand(0, 1) / rate (seconds)
  rate: 10

ratelimiter:
  port: 3000

  token_bucket:
    capacity: 4
    rate: 1

  fixed_window_counter:
    capacity: 4
    # seconds
    window_size: 1

  sliding_window_log:
    capacity: 4
    # seconds
    window_size: 1

  sliding_window_counter:
    capacity: 4
    # seconds
    window_size: 1
    # batch_size = window_size * batch_ratio
    batch_ratio: 0.02
