services:
  server:
    build: ./server
  ratelimiter:
    build: ./ratelimiter
    ports:
      - 3001:3001
    environment:
      ALGO: sliding_window_log
      LIMIT: 3
      RATE: 3
  cache:
    image: redis:7.4-alpine
