services:
  server:
    build: ./server
  ratelimiter:
    build: ./ratelimiter
    ports:
      - 3001:3001
    environment:
      ALGO: leaky_bucket
      LIMIT: 10
      RATE: 3
  cache:
    image: redis:7.4-alpine
