set dotenv-load

to_server:
  curl --header "Content-Type: application/json" --data '{"package": "123"}' localhost:3000

to_ratelimiter:
  curl --header "Content-Type: application/json" --data '{"package": "123"}' localhost:3001
