[package]
name = "server"
version = "0.1.0"
edition = "2024"

[dependencies]
appconfig = { path = "../appconfig" }
axum = "0.8.4"
chrono = "0.4.41"
tokio = { version = "1.45.1", features = ["rt-multi-thread"] }
