[package]
name = "server"
version = "0.1.0"
edition = "2021"

[dependencies]
http-body-util = "0.1.2"
hyper = "1.5.0"
hyper-util = { version = "0.1.9", features = ["http1", "server", "tokio"] }
tokio = { version = "1.41.0", features = ["macros", "net", "rt-multi-thread", "sync"] }
