[package]
name = "kvs"
version = "0.1.0"
authors = ["Khanh Duong Quoc <dqkqdlot@gmail.com>"]
description = "A key-value store"
edition = "2018"

[dev-dependencies]
assert_cmd = "2.0.16"
predicates = "3.1.2"
